### ISSUE TITLE
Glacier2/simpleChat detects dead router on shutdown

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-demos#102]
When killing the simpleChat server:
```
./server
^CDetected dead router - destroying all associated sessions 
```

The close callback should check the connection's exception and only print this message if the exception is not `ObjectAdapterDeactivationException`

**Comment by pepone** [comment]
@bentoi how can we get the exception here, the exception is not passed to the connection close callback

**Comment by bentoi** [comment]
The close callback could throw the connection's exception with {{Connection::throwException}}.
