### ISSUE TITLE
Add support for dark mode on iOS

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice-demos#103]
We should add support for the dark mode scheme. 

For instance, the chat demo currently looks a little off.
![IMG_DA2F263046B5-1](https://user-images.githubusercontent.com/2126835/66841207-57653100-ef37-11e9-8f8a-1f67950ce8ef.jpeg)

Once you log in, the chat input box text box and font are white which makes text invisible when you type.

**Comment by pepone** [comment]
We should just move the demos to SwiftUI see #95
