### ISSUE TITLE
Building Java demos against a source tree

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-demos#105]
Building the Java demos against an Ice for Java source tree doesn't really work right now despite what the instructions say.

It will pickup the Slice-to-Java compiler from the source tree but it won't pick up the JAR files from the source tree, it will still prefer picking up the JAR files form the maven central repository instead because the JAR files build in the source tree don't include metadata information.

On Debian, the demos are also built against the maven central JARs even if the JARs are installed with the debian package which installs both JAR files inside `/usr/share/java` and `/usr/share/maven-repo`.

We need to decide whether or not we still want to continue supporting this configuration.

If we want to continue supporting this configuration we'll either have to fix the dependencies to depend on JAR files (something like `implementation files('.../ice-compat-3.7.3.jar')`) or fix the repository configuration to exclude the `com.zeroc` group from the `mavenCentral` repository:
```
        mavenCentral {
            content {
                excludeGroup "com.zeroc"
            }
        }
```
This will force gadle to pickup the JAR files from the flatDir repository set in `ice.gradle`. This is however supported only with recent Gradle versions such as 5.6.4.

**Comment by pepone** [comment]
Fixed on 3.7 and master
