### ISSUE TITLE
Why are there no TypeScript/NodeJS Server demos?

### ISSUE THREAD

**Issue by IngwiePhoenix** [zeroc-ice/ice-demos#106]
Hello there!

While reading myself through the various demos to somewhat gain an understanding of Ice, I noticed that there were no server demos provided for Node, requiring to run another language's demo instead to have a running server.

I would simply like to know why this is. Does the Ice port of Node not support running as a server?

Kind regards,
Ingwie

**Comment by pepone** [comment]
There is only client side support with Ice for JavaScript, the supported features for the JavaScript mapping are described in https://doc.zeroc.com/ice/3.7/language-mappings/javascript-mapping

**Comment by IngwiePhoenix** [comment]
Ohh, I see. That is very unfortunate. So one has to run a server from C++ and connect JS clients. Well, that's too bad.

Thank you very much for your reply! But it seems like I won't be able to use Ice in my project then.

**Comment by pepone** [comment]
You can also use C#, Java, Python and Swift to write your Ice servers. It is something we might add eventually but we are not currently working on it.
