### ISSUE TITLE
Improve iOS/macOS Xcode demos to use storyboards

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-demos#13]
The demos still use XIB files for the interface, we should move to storyboards. This would for instance fix the `+[CATransaction synchronize] called within transaction` error that shows up on startup (caused by missing launch screen).

**Comment by externl** [comment]
Our macOS projects currently target `10.9` which does not support storyboards. I'm going to update them to be `10.10`.

**Comment by externl** [comment]
>+[CATransaction synchronize] called within transaction

@bentoi which demo do you see this with?
