### ISSUE TITLE
Java/android/hello

### ISSUE THREAD

**Issue by uapv1702675** [zeroc-ice/ice-demos#133]
Hello ! 

I'm not able to connect https://github.com/zeroc-ice/ice-demos/blob/3.7/java/android/hello/src/main/java/com/zeroc/hello/HelloApp.java with the hello cpp11 demo. I tried to change tcp port on 10004 on the android demo to match server.config but it still not working.

It works with Ice Discovery tho...

**Comment by pepone** [comment]
are you running the android demo from the simulator, what IP address is the server listening on?

**Comment by uapv1702675** [comment]
Ok I fixed it : I need to setup the tcp port to 45049 ( line 392 of the last link), I found this port number with the start message of the cpp client. Can you explain me why plz ? I'm kinda lost ( I'm not working directly on the demo but I'm doing a Univ project )

**Comment by pepone** [comment]
By default the server listens on   tcp 10000,  ssl 10001, ws 10002, and wss 10003 
https://github.com/zeroc-ice/ice-demos/blob/7a91b5461d8358753e766bd1b12cd505d1f093f1/cpp11/Ice/hello/config.server#L11

port 10004 is used for Admin object if enabled
https://github.com/zeroc-ice/ice-demos/blob/7a91b5461d8358753e766bd1b12cd505d1f093f1/cpp11/Ice/hello/config.server#L71

The simpler to check what address the server listens on, is to enable network tracing in the config https://github.com/zeroc-ice/ice-demos/blob/3.7/cpp11/Ice/hello/config.server#L39

**Comment by uapv1702675** [comment]
I've started from the IceDiscovery/hello server not /Ice/hello, so I have this config.file ( not edited ). It doesn't work by default with the  tcp port set at 10000

**Comment by pepone** [comment]
This demo works with the 2 servers to show different use cases:

* Ice/hello server uses a fixed address and port 10000, you must use this server when specifying the host address, in this case, the client application must know the address of the server

* IceDiscovery/hello this server doesn't use a fixed address and the client relies on the IceDiscovery location plug-in to find the server. In this case, you should select " Ice Discovery " to first discover the address of the server

see https://doc.zeroc.com/ice/3.7/ice-plugins/icediscovery

**Comment by uapv1702675** [comment]
Yep so ok I've missed that so far x'). Is there a way to print the Endpoint port once the Discovery  server launched ? 
I saw the client displays it but can't find how to do so server side.

Anyway thank u very much my IceLord for your time !

**Comment by pepone** [comment]
If you set `Ice.Trace.Network=3` in the server config file, you should see the address the server binds

https://doc.zeroc.com/ice/3.7/property-reference/ice-trace#id-.Ice.Trace.*v3.7-Ice.Trace.Network

**Comment by uapv1702675** [comment]
Thx very muchhhhh mann, you are so nice, have a nice day !
