### ISSUE TITLE
Under what circumstances is this setting required for compilation -- make CXXFLAGS=-std=c++11

### ISSUE THREAD

**Issue by liuty2006** [zeroc-ice/ice-demos#158]
The build system supports specifying additional preprocessor, compiler and linker options with the CPPFLAGS, CXXFLAGS and LDFLAGS variables. For example, to build the Ice C++98 mapping with -std=c++11, you can use:
make CXXFLAGS=-std=c++11

Under what circumstances is this setting required for compilation -- make CXXFLAGS=-std=c++11

**Comment by pepone** [comment]
If you build Ice with custom flags, you should use the same flags here, but it is otherwise not required to set CXXFLAGS or LDFLAGS
