### ISSUE TITLE
Add IceDiscovery support to csharp/Ice/wpf demo

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-demos#16]
It should support IceDiscovery like the other graphical "hello" demos.

**Comment by lejun** [comment]
How to get ip address by ice-discovery?

**Comment by bentoi** [comment]
You can obtain the Ice connection to the discovered server using the proxy `ice_getConnection` method. You can then obtain the connection information using the connection `getInfo` method. 

For example, you can do something like the following in C# to get the remote IP address:
```
Ice.ObjectPrx proxy = ...; // proxy resolved through IceDiscovery
for(Ice.ConnectionInfo p = proxy.getInfo(); p != null; p = p.underlying)
{
     if(p is Ice.IPConnectionInfo)
    {
        Ice.IPConnectionInfo ipinfo = p as Ice.IPConnectionInfo;
        System.Console.WriteLine("host: " + ipinfo.remoteAddress + " port: " + ipinfo.remotePort);
        break;
    }
}
```

**Comment by lejun** [comment]
@bentoi  thanks
