### ISSUE TITLE
Hi, i am a new beginner and studying the glacier module, i have some questions about sessionmanager.

### ISSUE THREAD

**Issue by jaCsharp** [zeroc-ice/ice-demos#61]
(1)If I want to combine the glacier module with ice register and icegird, is the sessionmanager in glacier necessary? 

 (2)I read the demo written with c++ about session manager, i am confused, could someone provide some demos written with csharp about how to create session manager by yourself?

thanks!

**Comment by bernardnormier** [comment]
For general questions about Ice and Ice services, please post on the forums:
https://forums.zeroc.com/categories/help-center

A Glacier2 SessionManager (and Session) can be implemented in any language, including C#.

We provide examples in C++ and Java:
https://github.com/zeroc-ice/ice-demos/blob/3.7/java/Database/library/Glacier2SessionManagerI.java

but currently not in C#.
