### ISSUE TITLE
Ice demo build failure for Android

### ISSUE THREAD

**Issue by ReeceHumphreys** [zeroc-ice/ice-demos#63]
Android build unable to find org.jetbrains.trove4j

`mavenCentral` should be replaced by `jcenter`
https://github.com/zeroc-ice/ice-demos/blob/3.6/java/Android/build.gradle#L42

**Comment by pepone** [comment]
That is odd, the build worked fine for me without additional repositories, using Android Studio 3.4.2

**Comment by ReeceHumphreys** [comment]
I am also using Android Studio 3.4.2 and could not get it to compile without changing it to `jcenter`. OS is Windows 10

**Comment by pepone** [comment]
Same here, in any case we should not remove `mavenCentral` as this is used to download Ice release JARs, we can add `jcenter` after it

**Comment by ReeceHumphreys** [comment]
Okay will updated and submit commit

**Comment by externl** [comment]
AFAICT `jcenter` includes `mavenCentral` packages
