### ISSUE TITLE
Library demo connection lost

### ISSUE THREAD

**Issue by ReeceHumphreys** [zeroc-ice/ice-demos#65]
The library demo is losing connection on both Android demo and Objective-c command line demo.

Here is error from Objective-C demo:
```
2019-08-07 15:58:26.048 client[39212:387686] warning: SessionRefreshThread: Outgoing.cpp:493: Ice::OperationNotExistException:
operation does not exist:
identity: `99697b81-9f93-488b-9402-f97015762549'
facet:
operation: refresh
```

**Comment by pepone** [comment]
The server is using the 3.7 version, we drop the refresh operation because it is using ACM to keep the session alive. We should do the same for 3.6

**Comment by bernardnormier** [comment]
Let's leave it as is. If you're interested in this demo for Android or iOS, upgrade to Ice 3.7.

**Comment by pepone** [comment]
I didn't see you already close this, I fixed it
