### ISSUE TITLE
Xamarin hello.iOS bugs

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-demos#93]
Two bugs when running this demo on my iPhone XR:
- the UI looks bad and is barely usable (in portrait, didn't try landscape)
- changing the hostname without changing anything else does not appear to "work" ... I keep getting "Connection refused", as if I didn't change the hostname. As soon as I change the mode to Oneway or something else, it works.

**Comment by pepone** [comment]
Fixed in def7328c1fc428da8d97f93a480470722ccf34f3
